services:
  - type: web
    name: smart-gift-planner
    env: python
    region: virginia
    buildCommand: "python3 -m uvicorn main:app --host 0.0.0.0 --port 10000 --workers 1"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    autoDeploy: true